version: "3"
services:
  messageHashStore:
    image: lyotam/message-hash-store:latest
    ports:
      - "8080:8080"
    networks:
      - message-hash-store-db
    links:
      - api-database
    depends_on:
      - api-database

  api-database:
    container_name: api-database
    image: mongo:3.2.4
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    networks:
      - message-hash-store-db
    command: mongod --smallfiles --logpath=/dev/null

networks:
  message-hash-store-db: